from app.database.models.address import Address
from app.database.models.base import Base
from app.database.models.breed import Breed
from app.database.models.client import Client
from app.database.models.code import Code
from app.database.models.patient import Patient
from app.database.models.phone_number import PhoneNumber
from app.database.models.species import Species
from app.database.models.transaction import Transaction
from app.database.models.vaccine import Vaccine
from app.database.models.medical_note import MedicalNote
